import React from 'react';

interface DownloadGeneratorProps {
  style: string;
  description: string;
  characteristics: string[];
  designTips: string[];
  metals: string[];
  woodFinishes: string[];
  colorPalette: string[];
  pdfUrl?: string;
}

const DownloadGenerator: React.FC<DownloadGeneratorProps> = ({
  style,
  description,
  characteristics,
  designTips,
  metals,
  woodFinishes,
  colorPalette,
  pdfUrl
}) => {
  const generatePDF = () => {
    if (pdfUrl) {
      // If PDF exists in database, download it directly
      const element = document.createElement('a');
      element.href = pdfUrl;
      element.download = `${style.replace(/\s+/g, '_')}_Style_Guide.pdf`;
      element.target = '_blank';
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    } else {
      // Fallback to generating text file
      generateTextFile();
    }
  };

  const generateTextFile = () => {
    const content = `
# ${style} Style Guide

## Description
${description}

## Key Characteristics
${characteristics.map(char => `• ${char}`).join('\n')}

## Design Tips
${designTips.map(tip => `• ${tip}`).join('\n')}

## Recommended Materials

### Metals
${metals.map(metal => `• ${metal}`).join('\n')}

### Wood Finishes
${woodFinishes.map(wood => `• ${wood}`).join('\n')}

## Color Palette
${colorPalette.map(color => `• ${color}`).join('\n')}

---
Generated by Style and Design Guide
${new Date().toLocaleDateString()}
    `;

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `${style.replace(/\s+/g, '_')}_Style_Guide.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  React.useEffect(() => {
    generatePDF();
  }, []);

  return null;
};

export default DownloadGenerator;